version: "2.6"
services:
  # eureka server 
  eureka-server:
    build:
      context: C:\Users\Alaa\eclipse-workspace\Eureka-server
      dockerfile: dockerFile
    container_name: eureka-server-container
    image: eureka-server-image
    ports:
      - "8761:8761"
    networks:
      - bored-network

  # mysql database      
  eventdb:
    container_name: eventdb
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=event_data_base
    volumes:
      - dbvol2:/var/lib/mysql
    ports:
      - "3311:3306"
    restart: always

  # mysql2 database      
  reclamationdb:
    container_name: reclamationdb
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=reclamation_data_base
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3310:3306"
    restart: always

  # postgresql database    



  event-service:
    build:
      context: C:\Users\Alaa\eclipse-workspace\GestionEventsMicroService
      dockerfile: dockerFile
    container_name: event-service-container
    image: event-service-image
    networks:
      - bored-network
    depends_on:
      - eventdb
      - eureka-server
    ports:
      - "8090:8090"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://eventdb:3306/event_data_base?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver

  reclamation-service:
    build:
      context: C:\Users\Alaa\Desktop\5eme Twin\microservices\Micro-Services-SmartSchool\GestionReclamationMicroservice
      dockerfile: dockerFile
    container_name: reclamation-service-container
    image: reclamation-service-image
    networks:
      - bored-network
    depends_on:
      - reclamationdb
      - eureka-server
    ports:
      - "8050:8050"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://reclamationdb:3306/reclamation_data_base?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
networks:
  bored-network:
    name: bored-network

volumes:
  dbvol:
  dbvol2:


