#From  openjdk:8-jdk
#Expose 8060
#ADD target/school-micro-user-1.0.jar  school-management.jar
#ENTRYPOINT ["java","-jar"," school-management.jar"]


FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD


COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/
RUN mvn clean package -DskipTests


FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=MAVEN_BUILD /build/target/school-micro-user-1.0.jar  /app/

ENTRYPOINT ["java", "-jar", "school-micro-user-1.0.jar"]