#FROM openjdk:8-jdk
#EXPOSE 8761
#ADD target/Eureka-service-1.0.jar Eureka.jar
#ENTRYPOINT ["java","-jar","Eureka.jar"]


FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD


COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/
RUN mvn clean package -DskipTests


FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=MAVEN_BUILD /build/target/Eureka-service-1.0.jar /app/

ENTRYPOINT ["java", "-jar", "Eureka-service-1.0.jar"]