version: "3.8"
services:
  eureka-server:
    build:
      context: ./Eureka-server/
      dockerfile: Dockerfile
    restart: always
    container_name: eureka-container
    image: eureka-image
    ports:
      - "8761:8761"
    networks:
      - bored-network
  userDB:
    container_name: userDB-container
    image: mongo
    restart: always
    networks:
      - bored-network
    ports:
      - "27017:27017"
    volumes:
      - userVolume:/data/db
  eventDB:
    container_name: eventDB-container
    restart: always
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=event_data_base
    volumes:
      - eventVolume:/var/lib/mysql
    ports:
      - "3311:3306"
  reclamationDB:
    container_name: reclamationDB-container
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=reclamation_data_base
    volumes:
      - reclamationVolume:/var/lib/mysql
    ports:
      - "3310:3306"
    restart: always
  fourmDB:
    container_name: fourmDB-container
    image: postgres
    restart: always
    networks:
      - bored-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fourmdatabase
      POSTGRES_USER: postgres
    ports:
      - "2345:5432"
  clubDB:
    container_name: clubDB-container
    image: postgres
    restart: always
    networks:
      - bored-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: club-service
      POSTGRES_USER: postgres
    volumes:
      - clubVolume:/var/lib/postgresql/data
    ports:
      - "2346:5432"
  nodeDB:
    container_name: nodeDB-container
    image: mongo
    restart: always
    networks:
      - bored-network
    ports:
      - "27019:27017"
    volumes:
      - nodeVolume:/data/db
  courseDB:
    container_name: courseDB-container
    image: mongo
    restart: always
    networks:
      - bored-network
    ports:
      - "27018:27017"
    volumes:
      - courseVolume:/data/db
 
  forum-service:
    build:
      context: ./forum-service
      dockerfile: Dockerfile
    container_name: forum-container
    image: forum-image
    networks:
      - bored-network
    depends_on:
      - fourmDB
      - eureka-server
    ports:
      - "8070:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:postgresql://fourmDB:5432/fourmdatabase
      - spring.datasource.username=postgres
      - spring.datasource.password=root
  user-service:
    build:
      context: ./school-micro-user
      dockerfile: Dockerfile
    container_name: user-container
    image: user-image
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - userDB
    ports:
      - "8060:8060"

    environment:

      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.data.mongodb.uri=mongodb://userDB:27017/userdatabase
      - spring.data.mongodb.database=userdatabase
  event-service:
    build:
      context: ./GestionEventsMicroService
      dockerfile: Dockerfile
    container_name: event-service-container
    image: event-service-image
    networks:
      - bored-network
    depends_on:
      - eventDB
      - eureka-server
    ports:
      - "8090:8090"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://eventdb:3306/event_data_base?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
  reclamation-service:
    build:
      context: ./GestionReclamationMicroservice/
      dockerfile: Dockerfile
    container_name: reclamation-container
    image: reclamation-image
    networks:
      - bored-network
    depends_on:
      - reclamationDB
      - eureka-server
    ports:
      - "8040:8040"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://reclamationDB:3306/reclamation_data_base?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
  club-service:
    build:
      context: ./club-service
      dockerfile: Dockerfile
    container_name: club-container
    image: club-image
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - clubDB
    ports:
      - "9000:9000"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:postgresql://clubDB:5432/club-service
      - spring.datasource.username=postgres
      - spring.datasource.password=root
  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    container_name: course-container
    image: course-image
    networks:
      - bored-network
    depends_on:
      - courseDB
      - eureka-server
    ports:
      - "9090:9090"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.data.mongodb.uri=mongodb://courseDB:27017/course
      - spring.data.mongodb.database=course
  node-service:
    build:
      context: ./node-service
      dockerfile: Dockerfile
    container_name: node-container
    image: node-image
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - nodeDB
    ports:
      - "5000:5000"
    environment:
      - eurekaHost=eureka-server
      - eurekaPort=8761
      
   
networks:
  bored-network:
    name: bored-network
volumes:
  eventVolume:
  reclamationVolume:
  userVolume:
  clubVolume:
  forumVolume:
  courseVolume:
  nodeVolume:
  
  
