version: "3.8"

services:

  # eureka server

  eureka-server:

    build:
      context: ./Eureka-server/
      dockerfile: dockerFile
    restart: always
    container_name: eureka-container
    image: eureka-image
    ports:
      - "8761:8761"
    networks:
      - bored-network
#------------------------------------------------------------Database------------------------------------------------------------
  # mysql database event-service
  eventDB:
    container_name: eventDB-container
    restart: always
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=event_data_base
    volumes:
      - eventVolume:/var/lib/mysql
    ports:
      - "3311:3306"
  # mysql database reclamation-service
  reclamationDB:
    container_name: reclamationDB-container
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=reclamation_data_base
    volumes:
      - reclamationVolume:/var/lib/mysql
    ports:
      - "3310:3306"
    restart: always

  # postgresql database forum-service

  fourmDB:
    container_name: fourmDB-container
    image: postgres
    restart: always
    networks:
      - bored-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: 
      POSTGRES_USER: postgres
    ports:
      - "2345:5432"
  # postgresql database club-service
  clubDB:
    container_name: clubDB-container
    image: postgres
    restart: always
    networks:
      - bored-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: club-service
      POSTGRES_USER: postgres
    volumes:
      - clubVolume:/var/lib/postgresql/data
    ports:
      - "2346:5432"
  # nosql database user-service
  userDB:
    container_name: userDB-container
    image: mongo
    restart: always
    networks:
      - bored-network
    ports:
      - "27017:27017"
    volumes:
      - userVolume:/data/db
  
 
  # ---------------------------------------services----------------------------------------------------
  #  forum-service
  forum-service:
    build:
      context: ./forum-service
      dockerfile: Dockerfile
    container_name: forum-container
    image: forum-service
    networks:
      - bored-network
    depends_on:
      - fourmDB
      - eureka-server
    ports:
      - "8070:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:postgresql://fourmDB:5432/fourmdatabase
      - spring.datasource.username=postgres
      - spring.datasource.password=root


  #user  service
  user-service:
    build:
      context: ./school-micro-user
      dockerfile: dockerFile
    container_name: user-container
    image: user-image
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - userDB
    ports:
      - "8060:8060"


    environment:

      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.data.mongodb.uri=mongodb://userDB:27017/userdatabase
      - spring.data.mongodb.database=userdatabase

  event-service:
    build:
      context: ./GestionEventsMicroService
      dockerfile: dockerFile
    container_name: event-service-container
    image: event-service-image
    networks:
      - bored-network
    depends_on:
      - eventDB
      - eureka-server
    ports:
      - "8090:8090"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://eventdb:3306/event_data_base?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver

  reclamation-service:
    build:
      context: ./GestionReclamationMicroservice/
      dockerfile: dockerFile
    container_name: reclamation-container
    image: reclamation-image
    networks:
      - bored-network
    depends_on:
      - reclamationDB
      - eureka-server
    ports:
      - "8040:8040"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://reclamationDB:3306/reclamation_data_base?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#club-service
  club-service:
    build:
      context: ./club-service
      dockerfile: Dockerfile
    container_name: club-service
    image: club-service
    networks:
      - bored-network
    depends_on:
      - eureka-server
      - clubDB
    ports:
      - "9000:9000"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:postgresql://clubDB:5432/club-service
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      
  spring-cloud-gateway-service:
     build:
       context: ./Cloud-Gateway
       dockerfile: dockerFile
     container_name: spring-cloud-container
     image: spring-cloud-service-image
     networks:
       - bored-network
     depends_on:
      - reclamation-service
      - event-service
      - eureka-server
     ports:
      - "8051:8051"
    
     environment: 
     #- eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/ 
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://reclamation-service-container:8040/
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: reclamationModule
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /reclamations/*
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://event-service-container:8090/
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: eventModule
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /events/*
      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://forum-service:8070/
      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: forumModule
      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path= /forums/*
      SPRING_CLOUD_GATEWAY_ROUTES[3]_URI: http://management-service-container:8060/
      SPRING_CLOUD_GATEWAY_ROUTES[3]_ID: userModule
      SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]: Path= /api/*
      
     
networks:
  bored-network:
    name: bored-network
  
volumes:
  eventVolume:
  reclamationVolume:
  userVolume:
  clubVolume:
  forumVolume:
  
  
