version: "2.6"
services:
  # eureka server 

  eureka-server:
    build:
      context: C:\Users\Alaa\eclipse-workspace\Eureka-server
      dockerfile: dockerFile
    container_name: eureka-server-container
    image: eureka-server-image
    ports:
      - "8761:8761"
    networks:
      - bored-network

  # mysql database      
  mysqldb1:
    container_name: mysqldb1
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=smart_school
    volumes:
      - dbvol2:/var/lib/mysql
    ports:
      - "3311:3306"
    restart: always
  # mysql2 database      
  mysqldb2:
    container_name: mysqldb2
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=smart_school2
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3310:3306"
    restart: always

  # postgresql database    



  event-service:
    build:
      context: C:\Users\Alaa\eclipse-workspace\GestionEventsMicroService
      dockerfile: dockerFile
    container_name: event-service-container
    image: event-service-image
    networks:
      - bored-network
    depends_on:
      - mysqldb2
      - eureka-server
    ports:
      - "8090:8090"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysqldb2:3306/smart_school2?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver

  event-service2:
    container_name: event-service-container2
    image: event-service-image
    networks:
      - bored-network
    depends_on:
      - mysqldb2
      - eureka-server
    ports:
      - "8091:8090"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysqldb2:3306/smart_school2?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=123456
  #  candidat-service    
  # candidat-service:

  #   build:
  #     context: C:\Users\Alaa\eclipse-workspace\Candidate
  #     dockerfile: dockerFile
  #   container_name: candidat-service-container
  #   image: candidat-service-image
  #   networks:
  #     - bored-network
  #   depends_on:
  #     - mysqldb1
  #     - eureka-server
  #   ports:
  #     - "8095:8095"
  #   environment:
  #     - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
  #     - spring.datasource.url=jdbc:mysql://mysqldb1:3306/smart_school?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  #     - spring.datasource.username=root
  #     - spring.datasource.password=123456

networks:
  bored-network:
    name: bored-network

volumes:
  dbvol:
  dbvol2:


