

#FROM openjdk:8-jdk
#EXPOSE 8090
#ADD target/GestionEventsMicroService-1.0.jar event.jar
#ENTRYPOINT ["java","-jar","event.jar"]


FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD


COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/
RUN mvn clean package -DskipTests


FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=MAVEN_BUILD /build/target/Cloud-Gateway-0.0.1-SNAPSHOT.jar  /app/

ENTRYPOINT ["java", "-jar", "Cloud-Gateway-0.0.1-SNAPSHOT.jar"]